// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function escaped(s) {
  return s.replace((/;/g), ";;");
}

function addStringDescriptor(acc, key, value) {
  if (value == null) {
    return /* () */0;
  } else {
    acc.push(key + (":" + escaped(value)));
    return /* () */0;
  }
}

function addIntegerDescriptor(acc, key, value) {
  if (value == null) {
    return /* () */0;
  } else {
    acc.push(key + (":" + String(value)));
    return /* () */0;
  }
}

function addBooleanDescriptor(acc, key, value) {
  if (!(value == null) && value) {
    acc.push(key);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function descriptor(windowDescription) {
  var title = windowDescription.title;
  var className = windowDescription.className;
  var regexpTitle = windowDescription.regexpTitle;
  var regexpClassName = windowDescription.regexpClassName;
  var instance = windowDescription.instance;
  var active = windowDescription.active;
  var last = windowDescription.last;
  var x = windowDescription.x;
  var y = windowDescription.y;
  var w = windowDescription.w;
  var h = windowDescription.h;
  var title$1 = title;
  var className$1 = className;
  var regexpTitle$1 = regexpTitle;
  var regexpClassName$1 = regexpClassName;
  var last$1 = last;
  var active$1 = active;
  var x$1 = x;
  var y$1 = y;
  var w$1 = w;
  var h$1 = h;
  var instance$1 = instance;
  var descriptors = /* array */[];
  addStringDescriptor(descriptors, "TITLE", title$1);
  addStringDescriptor(descriptors, "CLASS", className$1);
  addStringDescriptor(descriptors, "REGEXPTITLE", regexpTitle$1);
  addStringDescriptor(descriptors, "REGEXPCLASS", regexpClassName$1);
  addIntegerDescriptor(descriptors, "INSTANCE", instance$1);
  addBooleanDescriptor(descriptors, "ACTIVE", active$1);
  addBooleanDescriptor(descriptors, "LAST", last$1);
  addIntegerDescriptor(descriptors, "X", x$1);
  addIntegerDescriptor(descriptors, "Y", y$1);
  addIntegerDescriptor(descriptors, "W", w$1);
  addIntegerDescriptor(descriptors, "H", h$1);
  var body = descriptors.join("; ");
  return "[".concat(body, "]");
}

exports.descriptor = descriptor;
/* No side effect */
